name: CI CD Workflow
on: 
    push: 
        branches:
            - main

    pull_request:

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
              

            - name: Setup Node.js
              uses: actions/setup-node@v5
              with: 
                node-version: 22.13.0
            
            - name: Install Dependencies
              run: npm install
             
            - name: Install Typescript
              run: npm install typescript  
            
            - name: Run Build
              run: npm run build 
              
    deploy:
          runs-on: ubuntu-latest
          needs: build
          environment: production
          steps: 
                - name: Setup SSH
                  uses: webfactory/ssh-agent@v0.9.0
                  
                  with:
                    ssh-private-key: ${{ secrets.Actions_Key }}
                
                - name: Deploy to EC2
                  run: |
                    ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
                    source ~/.bashrc
                    cd /home/ubuntu/Simple_CI_CD
                    git pull origin main
                    /home/ubuntu/.nvm/versions/node/v22.13.0/bin/npm install
                    /home/ubuntu/.nvm/versions/node/v22.13.0/bin/npm run build
                    /home/ubuntu/.nvm/versions/node/v22.13.0/bin/pm2 restart HTTP-SERVER
                    EOF
              
               
       
                
                      

